### PR TITLE
Add TypeScript module definition file (#35)

### PR DESCRIPTION
**Pull request by bhdzllr**

### CODE REVIEW

**Comment by maximeh** [comment]
Thanks a lot for that!

**Comment by ulken** [comment]
@maximeh would it be possible to release a new tag with this?

**Comment by maximeh** [comment]
@ulken there you go: https://github.com/maximeh/leaflet.bouncemarker/releases/tag/v1.2.1

**Comment by ulken** [comment]
> @ulken there you go: https://github.com/maximeh/leaflet.bouncemarker/releases/tag/v1.2.1

Awesome — thank you for your quick response!

**Pull request merged**
