### PR TITLE
Adding dropping animation loop

### PR DESCRIPTION
**Pull request by petrabarus**
I can't seem to find how to make looping bounce animation like the one in Google Map Marker.
https://google-developers.appspot.com/maps/documentation/javascript/examples/full/marker-animations

So I created my own for my personal use. I just want to share this patch, just in case someone else also needs it.

To start the loop, all I need is to add a new field `loop` to the object.

``` javascript
marker.bounce({duration: 500, height: 100, loop: true});
```

and to end the loop, I execute this.

``` javascript
marker.bounce(null);
```

My implementation doesn't execute the callback function when the bouncing ends. Well, since the stopping is executed manually through `marker.bounce(null)`, I don't think putting callback will be that useful because we can call any function after we stop the bouncing.

### CODE REVIEW

**Comment by kelonye** [comment]
Any update on this? I see https://roadtrippers.com was able to apply this effect.

**Comment by maximeh** [comment]
Indeed this PR would need some love...

**Comment by maximeh** [comment]
@petrabarus any news ?

**Comment by kelonye** [comment]
Try https://github.com/hosuaby/Leaflet.SmoothMarkerBouncing

**Comment by maximeh** [comment]
@kelonye : Nice !

I don't know if I should try to implement such a function or if it's better to have separate plugins and thes simply shut down this PR.

**Comment by petrabarus** [comment]
Hi, I've been really busy lately. And I no longer use leaflet. But I'll try take a look this weekend.

**Comment by maximeh** [comment]
I know it's been *very* overdue but I have implemented this feature in another way (since the code has changed quite a lot).
But thank you very much for the idea !

**Pull request closed without merging**
